# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Session-Manager
version:      0.06
version_from: lib/Catalyst/Plugin/Session/Manager.pm
installdirs:  site
requires:
    Cache::FastMmap:               0
    Catalyst:                      5.3
    Class::Accessor:               0
    Class::Data::Inheritable:      0.04
    IO::File:                      0
    MIME::Base64:                  0
    NEXT:                          0
    Storable:                      0
    UNIVERSAL::require:            0
    URI:                           0
    URI::Find:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
